before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-date-time-dev libboost-thread-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev
language: cpp
script: mkdir build && cd build && cmake .. && make -j2 && make test
