language: cpp

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1

notifications:
  email: false

# All this duplication is required :/
matrix:
  include:
# == Release ==
# Linux
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      env:
        - CMAKE_BUILD_TYPE=Release
        - _CC=gcc-5
        - _CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-6
      env:
        - CMAKE_BUILD_TYPE=Release
        - _CC=gcc-6
        - _CXX=g++-6
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-3.9
      env:
        - CMAKE_BUILD_TYPE=Release
        - _CC=clang-3.9
        - _CXX=clang++-3.9

# OS X
    - os: osx
      compiler: clang
      sudo: false
      env:
        - CMAKE_BUILD_TYPE=Release


# == Debug ==
# Linux
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      env:
        - CMAKE_BUILD_TYPE=Debug
        - _CC=gcc-5
        - _CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-6
      env:
        - CMAKE_BUILD_TYPE=Debug
        - _CC=gcc-6
        - _CXX=g++-6
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-3.9
      env:
        - CMAKE_BUILD_TYPE=Debug
        - _CC=clang-3.9
        - _CXX=clang++-3.9

# OS X
    - os: osx
      compiler: clang
      sudo: false
      env:
        - CMAKE_BUILD_TYPE=Debug

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
    packages:
      - libboost-date-time1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-system1.55-dev
      - libsnappy-dev
      - liblz4-dev

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install snappy lz4;
    else
      sudo apt-get update;
      if [[ "$_CC" == "gcc-"* || "$_CC" == "clang-"* ]]; then
        sudo apt-get install "$_CC" "$_CXX";
      else
        sudo apt-get install libstdc++-5-dev;
      fi;
    fi
  - if [[ -n "$_CC" ]]; then
      export CC=$_CC;
    fi
  - if [[ -n "$_CXX" ]]; then
      export CXX=$_CXX;
    fi

script:
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" ..
  - make -j2
  - make test
