addons:
  apt:
    packages: []
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
env:
  global:
  - CTEST_OUTPUT_ON_FAILURE=1
  - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  - secure: COfJYVGLIBrJbWN3kCyx4Mr7DrdYIbNcTpa5ab+kqG8ErWy83L/jVTUnocnfAIFpFnUKX+EcMlz4g+ZFCMAakLNq9ZjKCYpRHHbwINkjr/CsDkjgyQjCALL8aW+dI5/8KBCmBNwf5PdOrHhcmdxQIgLrFBPQOcheXwt8zUFvmvQ=
language: cpp
matrix:
  include:
  - compiler: gcc-7
    dist: trusty
    env:
    - CMAKE_BUILD_TYPE=Debug
    - _CC=gcc-7
    - _CXX=g++-7
    os: linux
    sudo: required
notifications:
  email: false
script:
- echo $FOO
- git checkout --orphan travis_results
- git reset --hard
- 'echo ''{"result": "foobar"}'' > results.json

'
- git add results.json
- git commit -m 'Latest travis results'
- git remote add pushable "https://${GH_TOKEN}@github.com/thomasmoelhave/tpie.git"
- git push pushable travis_results
