# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - x64

# specify custom environment variables
environment:
  BOOST_ROOT: C:/Libraries/boost_1_60_0
  BOOST_LIBRARYDIR: C:/Libraries/boost_1_60_0/lib64-msvc-14.0

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:/projects/tpie

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages

# scripts to run before build
before_build:
  - cmd: cd C:/projects/tpie
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

build:
  parallel: true                           # enable MSBuild parallel builds
  project: C:/projects/tpie/build/tpie.sln # path to Visual Studio solution or project

test_script:
  - cmd: cd C:/projects/tpie
  - cmd: cd build
  - cmd: ctest -T Test --timeout 30 -j 2 --output-on-failure --no-compress-output -C "%CONFIG%" ctest || ver>nul

  # From https://gist.github.com/IlyaFinkelshteyn/237ef33c8c94057f0c4af1155e9bb043
  - ps: |
      $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
      $XSLInputElement.Load("https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl")
      $XSLInputElement.Transform((Resolve-Path .\Testing\*\Test.xml), (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))
